#server.port = 8080
#端口号
server:
  port: 8080
  servlet:
    context-path: /info

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#日志级别
logging:
  level:
    com.linbin: debug
